"""empty message

Revision ID: 928a24f15f12
Revises: 2312daf894f6
Create Date: 2025-11-13 22:38:44.066416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928a24f15f12'
down_revision = '2312daf894f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_planets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.drop_table('vehicle')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('character_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('gender')
        batch_op.drop_column('species')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('population')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('password')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('username')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='vehicle_character_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicle_pkey')
    )
    op.drop_table('user_favorite_planets')
    # ### end Alembic commands ###
